# Use official Python image
FROM python:latest

# Set working directory
WORKDIR /app

# COPY requirements.txt ./

# # Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt


RUN pip install flask flask-pymongo
# RUN pip install flask-session

EXPOSE 5000

# CMD ["python", "main.py"]

# pip install flask flask_pymongo
# python main.py