services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./python:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./media:/usr/share/nginx/html/media
      - ./play:/usr/share/nginx/html/play
    depends_on:
      - python
    network_mode: host

  mongo:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongadmin
    #   MONGO_INITDB_ROOT_PASSWORD: LikeAndSubscribe
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
    container_name: mongodb
    network_mode: host

  python:
    build: ./python/
    container_name: python
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - postfix
    volumes:
      - ./python:/app
      - ./media:/app/media
      - ./play:/app/play
    entrypoint: ["python", "main.py"]
    # entrypoint: ["tail", "-f", "/dev/null"]
    network_mode: host

  postfix:
    image: boky/postfix
    container_name: postfix
    ports:
      - 587:587
    environment:
      - ALLOWED_SENDER_DOMAINS=tim.cse356.compas.cs.stonybrook.edu
      - ALLOW_EMPTY_SENDER_DOMAINS=false
    network_mode: host