services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./python:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - python

  php:
    build: ./php_code/
    container_name: php
    expose:
      - 9000
    volumes:
      - ./php_code/:/var/www/html/

  mongo:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongadmin
    #   MONGO_INITDB_ROOT_PASSWORD: LikeAndSubscribe
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
    container_name: mongodb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=66cfe2a89ba30e1a6c70680a
    command: ["redis-server", "--requirepass", "66cfe2a89ba30e1a6c70680a"]

  python:
    build: ./python/
    container_name: python
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - ./python:/app
    entrypoint: ["tail", "-f", "/dev/null"]
